FileVersion = 1

[Project]
Name = "gtk-beef"
TargetType = "BeefLib"
StartupObject = "gtk_beef.Program"

[Configs.Debug.Linux64]
BuildKind = "StaticLib"
OtherLinkFlags = "$(LinkFlags) -lgtk-4 -lgio-2.0"
